// <auto-generated />
using System;
using DsK.ITSM.Security.EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DsK.ITSM.Security.EntityFramework.Migrations
{
    [DbContext(typeof(DsKitsmContext))]
    partial class DsKitsmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.AuthenticationProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthenticationProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuthenticationProviderType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthenticationProviderName" }, "IX_AuthenticationProviders");

                    b.ToTable("AuthenticationProviders");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07D45114DC");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Itsystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Systems");

                    b.ToTable("ITSystems", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Office365EmailGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Office365EmailGroups");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PermissionName" }, "IX_Permissions")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Priority__3214EC073C9C5F2E");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ItsystemId")
                        .HasColumnType("int")
                        .HasColumnName("ITSystemId");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItsystemId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestAssignedHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestAssignedHistory", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestMessageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("MessageDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestMessageHistory", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangedByUsernameUserId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_TransactionDateTime");

                    b.HasIndex("ChangedByUsernameUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestStatusHistory", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RequestTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__RequestT__3214EC07A8537660");

                    b.ToTable("RequestType", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleName" }, "IX_Roles")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK_RolePermissions_1");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Sop1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CopyProfileLike")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeskLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailGroups")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InternetAccess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneAccess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneExtension")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitlePosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SOP1", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Sop1system", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItsystemId")
                        .HasColumnType("int")
                        .HasColumnName("ITSystemId");

                    b.Property<int>("Sop1id")
                        .HasColumnType("int")
                        .HasColumnName("SOP1Id");

                    b.HasKey("Id");

                    b.HasIndex("ItsystemId");

                    b.ToTable("SOP1Systems", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserAuthenticationProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthenticationProviderId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthenticationProviderId" }, "IX_UserAuthenticationProviders_AuthenticationProviderId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserAuthenticationProviders_UserId");

                    b.ToTable("UserAuthenticationProviders");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IP");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserLogs_UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserPasswords_UserId");

                    b.ToTable("UserPasswords");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Allow")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PermissionId", "UserId" }, "IX_UserPermissions")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_UserPermissions_UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "IX_UserRoles")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRoles_RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TokenCreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TokenRefreshedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_UserAuthenticationProviderTokens");

                    b.HasIndex(new[] { "UserId" }, "IX_UserTokens_UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Request", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Category", "Category")
                        .WithMany("Requests")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_Categories");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Itsystem", "Itsystem")
                        .WithMany("Requests")
                        .HasForeignKey("ItsystemId")
                        .HasConstraintName("FK_Requests_ITSystems");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Priority", "Priority")
                        .WithMany("Requests")
                        .HasForeignKey("PriorityId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_Priority");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_RequestType");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "RequestedByUser")
                        .WithMany("Requests")
                        .HasForeignKey("RequestedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Requests_Users");

                    b.Navigation("Category");

                    b.Navigation("Itsystem");

                    b.Navigation("Priority");

                    b.Navigation("RequestType");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestAssignedHistory", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "AssignedToUser")
                        .WithMany("RequestAssignedHistories")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_RequestAssignedHistory_Requests");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Request", "Request")
                        .WithMany("RequestAssignedHistories")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestAssignedHistory_Requests1");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestMessageHistory", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Request", "Request")
                        .WithMany("RequestMessageHistories")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestMessageHistory_Requests1");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("RequestMessageHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RequestMessageHistory_Requests");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestStatusHistory", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "ChangedByUsernameUser")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("ChangedByUsernameUserId")
                        .HasConstraintName("FK_RequestStatusHistory_Requests");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Request", "Request")
                        .WithMany("RequestStatusHistories")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_RequestStatusHistory_Requests1");

                    b.Navigation("ChangedByUsernameUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RolePermission", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Permission", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permissions");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Role", "RoleNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("Role");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Sop1system", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Itsystem", "Itsystem")
                        .WithMany("Sop1systems")
                        .HasForeignKey("ItsystemId")
                        .HasConstraintName("FK_SOP1Systems_ITSystems");

                    b.Navigation("Itsystem");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserAuthenticationProvider", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.AuthenticationProvider", "AuthenticationProvider")
                        .WithMany("UserAuthenticationProviders")
                        .HasForeignKey("AuthenticationProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthenticationProviders_AuthenticationProviders");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("UserAuthenticationProviders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAuthenticationProviders_Users");

                    b.Navigation("AuthenticationProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserPassword", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("UserPasswords")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPasswords_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserPermission", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPermissions_Permissions");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPermissions_Users");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserRole", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.UserToken", b =>
                {
                    b.HasOne("DsK.ITSM.Security.EntityFramework.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.AuthenticationProvider", b =>
                {
                    b.Navigation("UserAuthenticationProviders");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Category", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Itsystem", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Sop1systems");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Priority", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Request", b =>
                {
                    b.Navigation("RequestAssignedHistories");

                    b.Navigation("RequestMessageHistories");

                    b.Navigation("RequestStatusHistories");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.RequestType", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DsK.ITSM.Security.EntityFramework.Models.User", b =>
                {
                    b.Navigation("RequestAssignedHistories");

                    b.Navigation("RequestMessageHistories");

                    b.Navigation("RequestStatusHistories");

                    b.Navigation("Requests");

                    b.Navigation("UserAuthenticationProviders");

                    b.Navigation("UserPasswords");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
